  name: flutter_mobile_app
  description: "A new Flutter project."
  
  version: 1.0.0+1

  environment:
    sdk: ^3.5.0

  dependencies:
    flutter:
      sdk: flutter
    flutter_svg: ^2.0.7

    cupertino_icons: ^1.0.8
    gap: ^3.0.1

  dev_dependencies:
    flutter_test:
      sdk: flutter
    
    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true
    assets:
      - assets/images/onboarding1.svg
      - assets/images/onboarding2.svg
      - assets/images/onboarding3.svg
      - assets/images/splash.svg
      - assets/images/header_auth.svg
      - assets/images/background_auth.svg
      - assets/images/background_auth2.svg
      - assets/icons/facebook.svg
      - assets/icons/line.svg
      - assets/icons/talk.svg
      - assets/icons/box_email.svg
      - assets/images/k.png
      - assets/images/d.png
      - assets/images/danang.png
      - assets/images/l.png
      - assets/images/m.png
      - assets/images/n.png
      - assets/images/danang2.png
      - assets/images/keyboard.png
      - assets/images/a.png
      - assets/images/b.png
      - assets/images/c.png
      - assets/images/d.png


      




  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display.ttf

